### ISSUE TITLE
/pigpen command not showing up in single player world

### ISSUE THREAD

**Issue by araguma** [Darkhax-Minecraft/PigPen#3]
The PigPen mod and the Bookshelf mod appear in the in-game mod list, but /pigpen shows up as an unknown command when I try to run it.

I'm using Forge 47.2.17 for Minecraft 1.20.1

**Comment by Darkhax** [comment]
In newer versions of Minecraft this command was replaced with the `/bookshelf font` command. This version of the command works with all fonts you have installed and is generally much better than the old one. If you haven't installed Bookshelf you can find it [here](https://www.curseforge.com/minecraft/mc-mods/bookshelf/files/4958302).

**Comment by ghost** [comment]
Hey I know it's probably old, but how do I encode a book to Pigpen? Commands only encode the item name.

**Comment by Darkhax** [comment]
@S00pergang The bookshelf command works fine with books, make sure you use the book subcommand. 

`/bookshelf font book minecraft:alt`

**Comment by ghost** [comment]
I tried that and the text in the book doesn't change

**Comment by Darkhax** [comment]
@S00pergang I've tried and it's working fine for me. Please open an issue on Bookshelf's github page with more info.

**Comment by boniblade** [comment]
@Darkhax The command doesn't seem to show anything on a server with Pigpen enabled?
For reference:

I am not an operator.
I attempted to use /bookshelf font say.
